# Generated by Django 3.2 on 2022-05-18 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 10, 35, 59, 703621)),
            preserve_default=False,
        ),
    ]
