# Generated by Django 3.2 on 2022-05-18 10:43

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Mpamba', 'Mpamba'), ('Airtel Money', 'Airtel Money'), ('Bank', 'Bank')], default='Cash', max_length=15)),
                ('expense_id', models.CharField(max_length=20, null=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('MWK', 'Malawian Kwacha')], default='MWK', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MWK', max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.ManyToManyField(to='expenses.ExpensePayment'),
        ),
    ]
