# Generated by Django 3.2 on 2022-05-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_batchnumber_created_at'),
        ('expenses', '0005_auto_20220518_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='batch_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.batchnumber'),
            preserve_default=False,
        ),
    ]
