# Generated by Django 3.0.9 on 2021-11-01 11:37

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ordered_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ordered_price_currency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier_name',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('ordered_price_currency', djmoney.models.fields.CurrencyField(choices=[('MWK', 'Malawian Kwacha')], default='MWK', editable=False, max_length=3)),
                ('ordered_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MWK', max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('supplier_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier')),
            ],
        ),
    ]
