# Generated by Django 3.0.9 on 2021-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211109_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='previous_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_in',
            field=models.IntegerField(default=0),
        ),
    ]
