# Generated by Django 3.0.9 on 2021-11-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211110_0103'),
        ('inventory', '0004_auto_20211109_1650'),
    ]

    operations = [
    ]
