# Generated by Django 4.1.1 on 2022-11-15 21:02

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.IntegerField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MWK', 'Malawian Kwacha')], default='MWK', editable=False, max_length=3, null=True),
        ),
    ]
