# Generated by Django 4.1.1 on 2023-01-11 13:35

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MWK', 'Malawian Kwacha')], default='MWK', editable=False, max_length=3, null=True),
        ),
    ]
