# Generated by Django 4.1.1 on 2022-11-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.IntegerField(unique=True),
        ),
    ]
