# Generated by Django 3.0.9 on 2021-11-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_merge_20211110_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='modified_on',
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
