# Generated by Django 3.0.9 on 2021-11-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211110_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch',
            field=models.CharField(max_length=50),
        ),
    ]
