# Generated by Django 3.0.9 on 2021-12-01 14:32

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20211113_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_cost_of_items',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MWK', max_digits=14),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_cost_of_items_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MWK', 'Malawian Kwacha')], default='MWK', editable=False, max_length=3),
        ),
    ]
