# Generated by Django 3.0.9 on 2021-12-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20211201_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created_at']},
        ),
    ]
