# Generated by Django 3.0.9 on 2021-12-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20211222_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ordered_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ordered_price_currency',
        ),
    ]
