# Generated by Django 3.2 on 2022-05-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20220517_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.batchnumber'),
        ),
    ]
