# Generated by Django 3.2 on 2022-05-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_stock_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='supplier_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
