# Generated by Django 3.2 on 2022-05-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_stock_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchnumber',
            name='batch_number',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
