# Generated by Django 3.2 on 2022-05-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_batchnumber_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchnumber',
            name='batch_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='batch',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='inventory.batchnumber'),
        ),
    ]
