# Generated by Django 3.2 on 2022-05-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_stock_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
