# Generated by Django 3.2 on 2022-05-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_stock_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.batchnumber'),
        ),
    ]
