# Generated by Django 3.2 on 2022-05-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_stock_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batchnumber'),
        ),
    ]
