# Generated by Django 3.2 on 2022-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_stock_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchnumber',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
