# Generated by Django 4.2.5 on 2023-10-01 11:04

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='MWK', max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='change_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MWK', 'Malawian Kwacha')], default='MWK', editable=False, max_length=3),
        ),
    ]
