# Generated by Django 4.1.1 on 2023-01-11 13:35

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundpayment',
            name='refund_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MWK', 'Malawian Kwacha')], default='MWK', editable=False, max_length=3, null=True),
        ),
    ]
