# Generated by Django 4.2.5 on 2023-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_order_change_order_change_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpamba', 'Mpamba'), ('Airtel Money', 'Airtel Money'), ('Bank', 'Bank')], default='Cash', max_length=15),
        ),
    ]
