# Generated by Django 3.0.9 on 2021-11-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20211109_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
    ]
