# Generated by Django 3.2.16 on 2023-01-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_barcode'),
        ('pos', '0004_alter_refundpayment_refund_amount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(null=True)),
                ('closing_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_quantity', models.IntegerField(default=0)),
                ('sale_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('session_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sessiontime')),
            ],
        ),
    ]
