# Generated by Django 4.1.1 on 2022-11-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_refundpayment_refund_amount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120, unique=True)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
