# Generated by Django 3.0.9 on 2021-11-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_orderitem_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
