# Generated by Django 3.0.9 on 2021-11-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_orderitem_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
