# Generated by Django 3.2.16 on 2023-01-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_openingquantity_sessiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingquantity',
            name='closing_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
