# Generated by Django 4.1.1 on 2022-11-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='date_time',
            field=models.TimeField(),
        ),
    ]
