# Generated by Django 4.1.1 on 2022-11-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_workinghours_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120, unique=True)),
                ('open_time', models.TimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='WorkingHours',
            new_name='ClosingTime',
        ),
        migrations.RenameField(
            model_name='closingtime',
            old_name='date_time',
            new_name='closing_time',
        ),
    ]
