# Generated by Django 3.0.9 on 2021-11-12 12:14

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20211111_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='laybyorders',
            name='sum_paid',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='MWK', max_digits=14),
        ),
        migrations.AddField(
            model_name='laybyorders',
            name='sum_paid_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MWK', 'Malawian Kwacha')], default='MWK', editable=False, max_length=3),
        ),
    ]
