# Generated by Django 4.1.1 on 2022-11-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_barcode'),
        ('pos', '0007_openingtime_rename_workinghours_closingtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_quantity', models.IntegerField(default=0)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
