# Generated by Django 4.1.1 on 2022-11-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_openingquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingquantity',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
