# Generated by Django 3.0.9 on 2021-12-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_auto_20211129_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='vat_p',
            field=models.FloatField(default=16.5),
        ),
    ]
