# Generated by Django 3.0.9 on 2021-12-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20211204_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.ManyToManyField(to='pos.Payment'),
        ),
    ]
