# Generated by Django 3.0.9 on 2021-08-10 23:02

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20210810_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MWK', max_digits=14, null=True),
        ),
    ]
