# Generated by Django 3.0.9 on 2021-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
