# Generated by Django 3.0.9 on 2021-12-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20211209_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.ManyToManyField(null=True, to='pos.Payment'),
        ),
    ]
