# Generated by Django 3.0.9 on 2021-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_auto_20211209_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.ManyToManyField(to='pos.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpamba', 'Mpamba'), ('Airtel Money', 'Airtel Money'), ('Lay By', 'Lay By')], default='Cash', max_length=15),
        ),
    ]
