# Generated by Django 3.0.9 on 2022-04-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_auto_20211219_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
