# Generated by Django 3.0.9 on 2022-04-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Lay By', 'Lay By')], default='Cash', max_length=15),
        ),
    ]
