# Generated by Django 3.0.9 on 2021-10-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_auto_20210816_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
    ]
