# Generated by Django 3.0.9 on 2022-04-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_auto_20220413_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpamba', 'Mpamba'), ('Airtel Money', 'Airtel Money'), ('Bank', 'Bank')], default='Cash', max_length=15),
        ),
    ]
