# Generated by Django 3.0.9 on 2022-04-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_auto_20220413_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_amount_currency',
        ),
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.ManyToManyField(null=True, to='pos.Payment'),
        ),
    ]
