# Generated by Django 3.0.9 on 2022-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20220414_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.ManyToManyField(to='pos.Payment'),
        ),
    ]
