# Generated by Django 3.0.9 on 2022-04-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_auto_20220414_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
