# Generated by Django 3.0.9 on 2022-04-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
