# Generated by Django 3.0.9 on 2022-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_refundorder_refundorderitem_refundpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorder',
            old_name='items',
            new_name='refunded_items',
        ),
        migrations.RemoveField(
            model_name='refundorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='refundorder',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='refundorder',
            name='payment_reference',
        ),
        migrations.AddField(
            model_name='refundorder',
            name='payments',
            field=models.ManyToManyField(to='pos.Payment'),
        ),
    ]
