# Generated by Django 3.0.9 on 2022-04-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_auto_20220421_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorderitem',
            old_name='ordered',
            new_name='returned',
        ),
        migrations.RenameField(
            model_name='refundorderitem',
            old_name='ordered_time',
            new_name='returned_time',
        ),
    ]
