# Generated by Django 3.0.9 on 2022-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_auto_20220421_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='payments',
            field=models.ManyToManyField(to='pos.RefundPayment'),
        ),
    ]
