# Generated by Django 3.0.9 on 2022-04-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_auto_20220421_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorderitem',
            name='initial_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
