# Generated by Django 3.0.9 on 2022-04-25 16:49

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_refundorderitem_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='MWK', max_digits=14),
        ),
    ]
