# Generated by Django 3.0.9 on 2022-04-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_auto_20220425_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorder',
            old_name='refund_total_cost',
            new_name='ordered_total_cost',
        ),
        migrations.RenameField(
            model_name='refundorder',
            old_name='refund_total_cost_currency',
            new_name='ordered_total_cost_currency',
        ),
    ]
