# Generated by Django 3.0.9 on 2022-05-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_auto_20220503_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorderitem',
            name='restock',
            field=models.BooleanField(default=True),
        ),
    ]
