# Generated by Django 3.2 on 2022-05-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_refundorderitem_restock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorderitem',
            old_name='restock',
            new_name='restock_to_inventory',
        ),
    ]
