# Generated by Django 3.2 on 2022-05-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_rename_restock_refundorderitem_restock_to_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundorderitem',
            name='returned',
        ),
    ]
