# Generated by Django 3.2 on 2022-05-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_remove_refundorderitem_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vat_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vat_cost_currency',
        ),
    ]
