# Generated by Django 3.2 on 2022-05-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0036_auto_20220520_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='reason_for_refund',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
