# Generated by Django 4.0.4 on 2022-06-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_alter_refundorder_reason_for_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
    ]
