# Generated by Django 4.0.4 on 2022-06-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0039_payment_service_fee_payment_service_fee_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service_fee_currency',
        ),
    ]
