# Generated by Django 3.0.9 on 2021-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20211218_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='quotation_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
